### PR TITLE
New Tree Lab

### PR DESCRIPTION
**Pull request by smasher164**
NOTE: The *.html files still need to be generated!
1) Moves Makefile-pizza and AVL worksheet to the in-lab.
2) Removes "path links followed" assignment from in-lab.
3) Alters postlab to require students to submit
	a) Binary search tree
	b) AVL tree
	c) A writeup containing a runtime comparison of both.

### CODE REVIEW

**Comment by zsd4yr** [comment]
Looks like there are two AVLTree constructors in the .cpp

**Comment by zsd4yr** [comment]
I suggest separating out node headers and .cpps

**Comment by zsd4yr** [comment]
any other files needed to make your code compile in postlab submissions, clarify this may be things like "AVLTree.cpp, BinarySearchTree.cpp, etc..."

**Comment by zsd4yr** [comment]
I think you should give advice on (1) the public private with root pass paradigm, and (2) using recursion for find/path/etc

**Comment by smasher164** [comment]
@zsd4yr 

> Looks like there are two AVLTree constructors in the .cpp

They were actually AVLNode and AVLTree constructors, not both AVLTree constructors.

> any other files needed to make your code compile in postlab submissions, clarify this may be things like "AVLTree.cpp, BinarySearchTree.cpp, etc..."

Agreed. Mentioned this under the "Things to submit" section.

> I think you should give advice on (1) the public private with root pass paradigm, and (2) using recursion for find/path/etc

Agreed. Mentioned this under the postlab writeup.

**Pull request merged**
